pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy to S3') {
            steps {
                sh 'aws s3 sync static-website-example/ s3://alexa-demo-$ENVIRONMENT/ --acl public-read'
            }
        }
    }
}